#!/usr/bin/env node
// Fetches HSK 2.0 single-character lists for levels 1-3 and a CC-CEDICT
// dump, then writes:
//   backend/src/main/resources/imports/hsk1.txt  (preserved if richer)
//   backend/src/main/resources/imports/hsk2.txt
//   backend/src/main/resources/imports/hsk3.txt
//   backend/src/main/resources/imports/cedict.sample.txt (HSK 1-3 single-char subset)
//
// Usage:  node scripts/import-data/fetch-hsk.mjs
//
// Sources:
//   HSK lists: https://github.com/glxxyz/hskhsk.com (HSK 2.0 official 2012)
//   CC-CEDICT: https://github.com/jtoy/crdict mirror of cedict_ts.u8
//              (CC-CEDICT is licensed CC BY-SA 4.0, see cc-cedict.org).
//
// Idempotent: re-running overwrites the generated files with the same
// deterministic contents.

import { writeFile, mkdir, readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(SCRIPT_DIR, "..", "..");
const IMPORTS_DIR = join(
  REPO_ROOT,
  "backend",
  "src",
  "main",
  "resources",
  "imports",
);

const HSK_SOURCES = {
  1: "https://raw.githubusercontent.com/glxxyz/hskhsk.com/master/data/lists/HSK%20Official%202012%20L1.txt",
  2: "https://raw.githubusercontent.com/glxxyz/hskhsk.com/master/data/lists/HSK%20Official%202012%20L2.txt",
  3: "https://raw.githubusercontent.com/glxxyz/hskhsk.com/master/data/lists/HSK%20Official%202012%20L3.txt",
};
const CEDICT_URL =
  "https://raw.githubusercontent.com/jtoy/crdict/master/cedict_ts.u8";

async function fetchText(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`GET ${url} → ${res.status}`);
  return await res.text();
}

function isSingleHanzi(ch) {
  const cp = ch.codePointAt(0);
  return (
    (cp >= 0x4e00 && cp <= 0x9fff) || (cp >= 0x3400 && cp <= 0x4dbf)
  );
}

async function loadHskLevel(level) {
  // HSK lists are word lists; we extract every unique single hanzi that
  // appears in any word at this level.
  const raw = await fetchText(HSK_SOURCES[level]);
  const seen = new Set();
  for (const line of raw.split(/\r?\n/)) {
    for (const ch of line.trim()) {
      if (isSingleHanzi(ch)) seen.add(ch);
    }
  }
  return [...seen];
}

function parseCedictLine(line) {
  // Format: TRAD SIMP [pin1 yin2] /m1/m2/.../
  if (!line || line.startsWith("#")) return null;
  const m = line.match(/^(\S+)\s+(\S+)\s+\[([^\]]+)\]\s+\/(.+)\/\s*$/);
  if (!m) return null;
  const [, trad, simp, pinyin, body] = m;
  const meanings = body.split("/").filter(Boolean);
  return { trad, simp, pinyin, meanings, raw: line };
}

async function loadCedictForChars(wantedChars) {
  const raw = await fetchText(CEDICT_URL);
  // Keep best entry per simplified char (first non-empty meanings wins,
  // matching the JVM importer's heuristic).
  const best = new Map();
  for (const line of raw.split(/\r?\n/)) {
    const e = parseCedictLine(line);
    if (!e) continue;
    if ([...e.simp].length !== 1) continue;
    if (!wantedChars.has(e.simp)) continue;
    const existing = best.get(e.simp);
    if (!existing || existing.meanings.length === 0) {
      best.set(e.simp, e);
    }
  }
  return best;
}

function formatHskFile(level, chars) {
  const header = [
    `# HSK 2.0 Level ${level} character list bundled with the backend.`,
    `# Format: <character> <hsk-level>`,
    `# Source: ${HSK_SOURCES[level]}`,
    ``,
  ].join("\n");
  return header + chars.map((c) => `${c} ${level}`).join("\n") + "\n";
}

function formatCedictFile(entriesByChar) {
  const header = [
    `# CC-CEDICT subset bundled for development & tests (HSK 1-3 single chars).`,
    `# Generated by scripts/import-data/fetch-hsk.mjs.`,
    `# CC-CEDICT is licensed CC BY-SA 4.0; full dump: https://www.mdbg.net/chinese/dictionary?page=cc-cedict`,
    `# For production, set kekao.import.cedict-path to the real dump.`,
    `# Format (one entry per line):`,
    `#   Traditional Simplified [pin1 yin1] /meaning1/meaning2/.../`,
    ``,
  ].join("\n");
  const lines = [...entriesByChar.values()]
    .sort((a, b) => a.simp.localeCompare(b.simp))
    .map((e) => e.raw.trim());
  return header + lines.join("\n") + "\n";
}

async function main() {
  if (!existsSync(IMPORTS_DIR)) {
    await mkdir(IMPORTS_DIR, { recursive: true });
  }
  console.log("Fetching HSK character lists…");
  const byLevel = {};
  for (const level of [1, 2, 3]) {
    byLevel[level] = await loadHskLevel(level);
    console.log(`  HSK ${level}: ${byLevel[level].length} chars`);
  }
  // Levels are nested by convention (chars in L1 also count as known for L2),
  // but for our import map each char gets its lowest HSK level.
  const lowestLevel = new Map();
  for (const level of [3, 2, 1]) {
    for (const ch of byLevel[level]) lowestLevel.set(ch, level);
  }
  const buckets = { 1: [], 2: [], 3: [] };
  for (const [ch, lvl] of lowestLevel) buckets[lvl].push(ch);
  for (const lvl of [1, 2, 3]) buckets[lvl].sort();

  const allChars = new Set(lowestLevel.keys());
  console.log(
    `Total unique HSK 1-3 single hanzi: ${allChars.size} (target ~600)`,
  );

  console.log("Fetching CC-CEDICT…");
  const entries = await loadCedictForChars(allChars);
  console.log(`  matched ${entries.size}/${allChars.size} chars in CC-CEDICT`);
  const missing = [...allChars].filter((c) => !entries.has(c));
  if (missing.length) {
    console.warn(`  missing CC-CEDICT for: ${missing.join(" ")}`);
  }

  for (const lvl of [1, 2, 3]) {
    const out = join(IMPORTS_DIR, `hsk${lvl}.txt`);
    // Preserve any human-edited hsk1.txt only if generated content matches
    // — overwrite is fine because the importer is idempotent.
    await writeFile(out, formatHskFile(lvl, buckets[lvl]), "utf8");
    console.log(`  wrote ${out}`);
  }

  const cedictPath = join(IMPORTS_DIR, "cedict.sample.txt");
  await writeFile(cedictPath, formatCedictFile(entries), "utf8");
  console.log(`  wrote ${cedictPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
