#!/usr/bin/env node
// Reusable corpus importer (TASK: classical-texts extension).
//
// Given any Chinese-language corpus (a URL or a local file), this script
// extracts every unique single hanzi, subtracts the characters already
// covered by the bundled HSK lists, and emits the data the JVM importer needs
// to load the *missing* characters into the `hanzi` table:
//
//   backend/src/main/resources/imports/<name>.txt
//       one character per line — consumed as a "corpus list" (no HSK level).
//   backend/src/main/resources/imports/<name>.cedict.txt
//       the CC-CEDICT lines for those characters, so the importer can resolve
//       pinyin + English meanings offline.
//
// Usage:
//   node scripts/import-data/import-corpus.mjs \
//     --source <url|path> --name three-kingdoms [--cedict <url|path>]
//
// The module also exports its building blocks so other scripts (e.g.
// build-three-kingdoms.mjs) can reuse them without shelling out.

import { writeFile, readFile, readdir, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, join, isAbsolute } from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
export const REPO_ROOT = join(SCRIPT_DIR, "..", "..");
export const IMPORTS_DIR = join(
  REPO_ROOT,
  "backend",
  "src",
  "main",
  "resources",
  "imports",
);

const DEFAULT_CEDICT_URL =
  "https://raw.githubusercontent.com/jtoy/crdict/master/cedict_ts.u8";

export function isSingleHanzi(ch) {
  const cp = ch.codePointAt(0);
  return (cp >= 0x4e00 && cp <= 0x9fff) || (cp >= 0x3400 && cp <= 0x4dbf);
}

/** Reads a corpus from an http(s) URL or a local filesystem path. */
export async function readSource(source) {
  if (/^https?:\/\//.test(source)) {
    const res = await fetch(source);
    if (!res.ok) throw new Error(`GET ${source} → ${res.status}`);
    return await res.text();
  }
  const path = isAbsolute(source) ? source : join(REPO_ROOT, source);
  return await readFile(path, "utf8");
}

/** Every unique single hanzi in the text, in first-seen order. */
export function extractHanzi(text) {
  const seen = new Set();
  for (const ch of text) {
    if (isSingleHanzi(ch)) seen.add(ch);
  }
  return [...seen];
}

/** Characters already present in the bundled HSK list files. */
export async function loadCoveredChars() {
  const covered = new Set();
  const files = (await readdir(IMPORTS_DIR)).filter((f) => /^hsk\d+\.txt$/.test(f));
  for (const file of files) {
    const raw = await readFile(join(IMPORTS_DIR, file), "utf8");
    for (const line of raw.split(/\r?\n/)) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) continue;
      const ch = trimmed.split(/\s+/)[0];
      if (ch) covered.add(ch);
    }
  }
  return covered;
}

function parseCedictLine(line) {
  if (!line || line.startsWith("#")) return null;
  const m = line.match(/^(\S+)\s+(\S+)\s+\[([^\]]+)\]\s+\/(.+)\/\s*$/);
  if (!m) return null;
  const [, , simp, , body] = m;
  const meanings = body.split("/").filter(Boolean);
  return { simp, meanings, raw: line.trim() };
}

/** Best CC-CEDICT entry per simplified char, restricted to `wanted`. */
export async function loadCedictForChars(wanted, cedictSource) {
  const raw = await readSource(cedictSource);
  const best = new Map();
  for (const line of raw.split(/\r?\n/)) {
    const e = parseCedictLine(line);
    if (!e) continue;
    if ([...e.simp].length !== 1) continue;
    if (!wanted.has(e.simp)) continue;
    const existing = best.get(e.simp);
    if (!existing || existing.meanings.length === 0) best.set(e.simp, e);
  }
  return best;
}

function formatCorpusList(name, chars) {
  const header = [
    `# Corpus character list: ${name}.`,
    `# Generated by scripts/import-data/import-corpus.mjs — do not edit by hand.`,
    `# Format: one simplified character per line (imported with no HSK level).`,
    ``,
  ].join("\n");
  return header + chars.join("\n") + "\n";
}

function formatCedictSubset(name, entriesByChar) {
  const header = [
    `# CC-CEDICT subset for corpus "${name}".`,
    `# Generated by scripts/import-data/import-corpus.mjs.`,
    `# CC-CEDICT is licensed CC BY-SA 4.0; full dump: https://www.mdbg.net/chinese/dictionary?page=cc-cedict`,
    `# Format: Traditional Simplified [pin1 yin1] /meaning1/meaning2/.../`,
    ``,
  ].join("\n");
  const lines = [...entriesByChar.values()]
    .sort((a, b) => a.simp.localeCompare(b.simp))
    .map((e) => e.raw);
  return header + lines.join("\n") + "\n";
}

/**
 * Computes and writes the import resources for the missing characters of a
 * corpus. Returns a summary report.
 */
export async function importCorpus({ source, name, cedict = DEFAULT_CEDICT_URL, text }) {
  if (!existsSync(IMPORTS_DIR)) await mkdir(IMPORTS_DIR, { recursive: true });
  const corpusText = text ?? (await readSource(source));
  const allChars = extractHanzi(corpusText);
  const covered = await loadCoveredChars();
  const missing = allChars.filter((c) => !covered.has(c)).sort();

  const entries = await loadCedictForChars(new Set(missing), cedict);
  const missingCedict = missing.filter((c) => !entries.has(c));

  const listPath = join(IMPORTS_DIR, `${name}.txt`);
  const cedictPath = join(IMPORTS_DIR, `${name}.cedict.txt`);
  await writeFile(listPath, formatCorpusList(name, missing), "utf8");
  await writeFile(cedictPath, formatCedictSubset(name, entries), "utf8");

  return {
    totalUnique: allChars.length,
    covered: allChars.length - missing.length,
    missing: missing.length,
    cedictMatched: entries.size,
    cedictMissing: missingCedict.length,
    missingCedictSample: missingCedict.slice(0, 20),
    listPath,
    cedictPath,
  };
}

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i += 1) {
    const token = argv[i];
    if (token.startsWith("--")) {
      const key = token.slice(2);
      const value = argv[i + 1] && !argv[i + 1].startsWith("--") ? argv[(i += 1)] : "true";
      args[key] = value;
    }
  }
  return args;
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  if (!args.source || !args.name) {
    console.error("Usage: import-corpus.mjs --source <url|path> --name <slug> [--cedict <url|path>]");
    process.exit(2);
  }
  console.log(`Importing corpus "${args.name}" from ${args.source}…`);
  const report = await importCorpus({
    source: args.source,
    name: args.name,
    cedict: args.cedict ?? DEFAULT_CEDICT_URL,
  });
  console.log(`  unique hanzi:       ${report.totalUnique}`);
  console.log(`  already covered:    ${report.covered}`);
  console.log(`  missing (new):      ${report.missing}`);
  console.log(`  matched in CEDICT:  ${report.cedictMatched}`);
  console.log(`  no CEDICT entry:    ${report.cedictMissing}`);
  if (report.cedictMissing) {
    console.log(`  sample missing:     ${report.missingCedictSample.join(" ")}`);
  }
  console.log(`  wrote ${report.listPath}`);
  console.log(`  wrote ${report.cedictPath}`);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
