// On-demand loader for the full text of Romance of the Three Kingdoms.
//
// The novel is split into 120 per-chapter JSON files under
// `frontend/public/three-kingdoms/` (generated by
// scripts/import-data/build-three-kingdoms.mjs). Chapters are fetched lazily so
// the SPA bundle stays small.

import type { WritingLesson, WritingText } from "@/lib/writing-texts";

const BASE = "/three-kingdoms";

export interface ChapterMeta {
  chapter: number;
  title: string;
  sentences: number;
  file: string;
}

interface Manifest {
  title: string;
  source: string;
  chapters: ChapterMeta[];
}

interface ChapterPayload {
  chapter: number;
  title: string;
  texts: WritingText[];
}

export async function fetchChapterManifest(): Promise<ChapterMeta[]> {
  const res = await fetch(`${BASE}/manifest.json`);
  if (!res.ok) throw new Error(`Could not load chapter list (${res.status})`);
  const manifest = (await res.json()) as Manifest;
  return manifest.chapters;
}

export async function fetchChapterLesson(meta: ChapterMeta): Promise<WritingLesson> {
  const res = await fetch(`${BASE}/${meta.file}`);
  if (!res.ok) throw new Error(`Could not load chapter ${meta.chapter} (${res.status})`);
  const payload = (await res.json()) as ChapterPayload;
  return {
    id: `three-kingdoms-${payload.chapter}`,
    title: payload.title,
    description: "Romance of the Three Kingdoms",
    level: 3,
    texts: payload.texts,
  };
}
